### ISSUE TITLE
JBR 17 + JCEF for linux aarch64 release is broken

### ISSUE THREAD

**Issue by jokaorgua** [JetBrains/JetBrainsRuntime#147]
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_fd-17.0.3-linux-aarch64-b423.10.tar.gz

this link gives some 85 bytes file. not the needed archive

**Comment by vprovodin** [comment]
The issue is tracked by the ticket https://youtrack.jetbrains.com/issue/JBR-4451

**Comment by jebeaudet** [comment]
Any updates on this? Thanks

To others trying to find a working build, it seems the latest one still working is [this one](https://github.com/JetBrains/JetBrainsRuntime/releases/tag/jbr17.0.3b423.10)

**Comment by jebeaudet** [comment]
@vprovodin, in the [latest release](https://github.com/JetBrains/JetBrainsRuntime/releases/tag/jbr-release-17.0.5b653.14), the [jbrsdk](https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-17.0.5-osx-aarch64-b653.14.tar.gz) and [jbr jcef](https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk_jcef-17.0.5-osx-aarch64-b653.14.tar.gz) are not working. JBR vanilla does seem to work though. I've only tested the tarballs.

**Comment by vprovodin** [comment]
@jebeaudet What builds are you talking about?
1. Please not this issue was opened for linux-aarch64.
2. If you detected some issues (with jcef) could you please provide us with details - describe issue, provide logs and  steps to reproduce...
3. it would be better to create a separate ticket
4. it would be better to create it in https://youtrack.jetbrains.com/ against JBR project

**Comment by jebeaudet** [comment]
Oups my bad, very sorry about that. I recently switch to macos and tend to interchange macos/linux when downloading binaries out of habit.

As for the corrupted releases, seems like the problem was on my end and required to allow the _whole folder_ as trusted in macOS and not just the binary. If anyone stumble here while googling, running `sudo xattr -cr /Path/To/Extracted/JBR` did it. 

Again, sorry about that and thanks for the follow up.
