### ISSUE TITLE
Duplicated files with different casing clash on JBR17 releases.

### ISSUE THREAD

**Issue by fabianhjr** [JetBrains/JetBrainsRuntime#163]
Reproduction:

`git checkout jb17.0.3-b469.37`

```
tree ./test/jdk/jb/java/awt/*ont/
├── [...]
└── TextLayout
    └── DrawTest.java
./test/jdk/jb/java/awt/font/
└── TextLayout
    └── DrawTest.java
```

```
sha256sum test/jdk/jb/java/awt/font/TextLayout/DrawTest.java test/jdk/jb/java/awt/Font/TextLayout/DrawTest.java
da99ed8bc55dca3ad159300aa503906fcb3687d510c4a4db7b061f5ee16e7439  test/jdk/jb/java/awt/font/TextLayout/DrawTest.java
da99ed8bc55dca3ad159300aa503906fcb3687d510c4a4db7b061f5ee16e7439  test/jdk/jb/java/awt/Font/TextLayout/DrawTest.java
```

This affects case-insesitive filesystems.

**Comment by Mindavi** [comment]
Just to be clear, the issue is that the paths are identical other than casing, and case-insensitive filesystems like MacOS' filesystem will handle it differently from case-sensitive filesystems like linux'. Since we generate a hash based on contents, this is a bit annoying since the hashes are different due to the clashing pathnames.

See the PR in nixpkgs for context: https://github.com/NixOS/nixpkgs/pull/183763

**Comment by huantianad** [comment]
Is this as simple as removing the duplicate file at `./test/jdk/jb/java/awt/font/TextLayout/DrawTest.java`? I can make a quick PR if that's the only issue here.

**Comment by fabianhjr** [comment]
Unsure about which of the two should be removed though (not familiar with the project / compiling / testing)

**Comment by huantianad** [comment]
The one at `font/TextLayout/DrawTest.java` seems to be the extra one, since its the only file in the folders.
