### ISSUE TITLE
Where is the jetbrains.api namespace in the build?

### ISSUE THREAD

**Issue by FabianHummel** [JetBrains/JetBrainsRuntime#185]
I want to create a Swing/Awt Window with the help of the classes found inside the src/jetbrains.api folder, but I cannot find nor use those in my project. Do I need to compile the solution myself?

**Comment by FabianHummel** [comment]
Found it, I needed to run the Gensrc.java together with the repository source code. Why is it not documented?...

**Comment by lwlha** [comment]
Hello, How did you ultimately solve this problem?

**Comment by YaaZ** [comment]
Hi! Sorry, I missed the original question. It was not documented because it was only intended for internal use (just yet). But here's the correct usage:
1. Run `configure` like you usually do for building the JDK
2. `make jbr-api`
This will build a jar library in `build/<conf>/jbr-api`, which you can then use via `JBR` class
